# Generated by Django 4.1.13 on 2025-03-13 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import password_manager.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('sha512hash', models.BinaryField(editable=True, max_length=64, unique=True)),
                ('wrapped_key', models.BinaryField(max_length=256)),
                ('hmac_wrapped_key', models.BinaryField(max_length=256)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('alg_unwrap_key', models.CharField(choices=[('xchacha20', 'XChaCha20-Poly1305'), ('aesgcm', 'AES-GCM256')], default='aesgcm', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('auth_words_hash', models.BinaryField(blank=True, max_length=64, null=True)),
                ('hmac_words_hash', models.BinaryField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_users_groups', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users_permissions', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', password_manager.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_data', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Data Item',
                'verbose_name_plural': 'User Data Items',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RememberedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('device_identifier', models.BinaryField(max_length=64)),
                ('encrypted_auth_data', models.BinaryField(max_length=512)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remembered_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device_identifier')},
            },
        ),
    ]
